/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicImagenSplatRouteImport } from './routes/api/public/imagen.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImagenSplatRoute = ApiPublicImagenSplatRouteImport.update({
  id: '/api/public/imagen/$',
  path: '/api/public/imagen/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/imagen/$': typeof ApiPublicImagenSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/imagen/$': typeof ApiPublicImagenSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/imagen/$': typeof ApiPublicImagenSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/imagen/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/imagen/$'
  id: '__root__' | '/' | '/api/public/imagen/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicImagenSplatRoute: typeof ApiPublicImagenSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/imagen/$': {
      id: '/api/public/imagen/$'
      path: '/api/public/imagen/$'
      fullPath: '/api/public/imagen/$'
      preLoaderRoute: typeof ApiPublicImagenSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicImagenSplatRoute: ApiPublicImagenSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
